/*
 * Copyright (C) 2024 Hedera Hashgraph, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hedera.cryptography.utils.test.fixtures.rng;

import edu.umd.cs.findbugs.annotations.NonNull;
import java.util.Random;

public class RandomUtils {
    /**
     * Utility class constructor.
     */
    private RandomUtils() {
        // Private constructor to prevent instantiation.
    }

    /**
     * Creates a new {@link Random} instance with a random seed which is printed to the console.
     *
     * @return a new {@link Random} instance
     */
    public static Random create() {
        final Random random = new Random();
        final long seed = random.nextLong();
        System.out.println("Random seed: " + seed);
        return new Random(seed);
    }

    /**
     * Generates random bytes.
     *
     * @param size the size of the byte array to generate
     *
     * @return the generated byte array
     */
    public static @NonNull byte[] randomBytes(final int size) {
        return randomBytes(create(), size);
    }

    /**
     * Generates random bytes.
     *
     * @param random the random number generator
     * @param size the size of the byte array to generate
     *
     * @return the generated byte array
     */
    public static @NonNull byte[] randomBytes(@NonNull final Random random, final int size) {
        final byte[] bytes = new byte[size];
        random.nextBytes(bytes);
        return bytes;
    }
}
