/*
 * Copyright (C) 2024 Hedera Hashgraph, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hedera.cryptography.utils.test.fixtures.rng;

import edu.umd.cs.findbugs.annotations.NonNull;
import java.util.Random;

/**
 * A random number generator that is always seeded with a fixed seed.
 */
public class SeededRandom extends Random {
    private final long seed;
    private boolean initialized = false;

    /**
     * Creates a new seeded random number generator.
     */
    public SeededRandom() {
        this(new Random().nextLong(), true);
    }

    /**
     * Creates a new seeded random number generator with the given seed.
     *
     * @param seed the seed
     */
    public SeededRandom(long seed) {
        this(seed, true);
    }

    /**
     * Creates a new seeded random number generator with the given seed and whether to print the seed to the console.
     *
     * @param seed      the seed
     * @param printSeed whether to print the seed to the console
     */
    public SeededRandom(long seed, boolean printSeed) {
        super(seed);
        this.seed = seed;
        if (printSeed) {
            System.out.println("Random with seed: " + seed);
        }
    }

    /**
     * Throws an {@link UnsupportedOperationException} as the seed of a {@link SeededRandom} instance cannot be
     * changed.
     */
    @Override
    public synchronized void setSeed(long seed) {
        if (!initialized) {
            super.setSeed(seed);
            initialized = true;
        } else {
            throw new UnsupportedOperationException("Cannot change the seed of a SeededRandom instance");
        }
    }

    /**
     * Returns the seed of this random number generator.
     *
     * @return the seed
     */
    public long getSeed() {
        return seed;
    }

    /**
     * Generates random bytes.
     *
     * @param size the size of the byte array to generate
     * @return the generated byte array
     */
    public @NonNull byte[] randomBytes(final int size) {
        final byte[] bytes = new byte[size];
        super.nextBytes(bytes);
        return bytes;
    }
}
