// SPDX-License-Identifier: Apache-2.0
package com.hedera.cryptography.ceremony.crypto;

import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.SecureRandom;
import java.security.cert.X509Certificate;

/**
 * This class is responsible for generating and loading the keys and certificates {@link KeysAndCertsGenerator} used
 * in the system.
 * <p>
 * The algorithms and key sizes used here are chosen in accordance with the IAD-NSA Commercial National Security
 * Algorithm (CNSA) Suite, and TLS 1.2, as implemented by the SUN and SunEC security providers, using the JCE Unlimited
 * Strength Jurisdiction files. The TLS suite used here is called TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384. Java uses the
 * NIST p-384 curve specified by the CNSA for ECDH and ECDSA.
 * <p>
 * To aid in key recovery, this is designed so that all of the keys here are generated by deterministic functions of a
 * triplet (master key, swirld ID, member ID), which are passed in to the constructor. When TLS key agreement needs a
 * source of random numbers, it uses SecureRandom with "SHA1PRNG", which calls the underlying operating system's
 * /dev/random and /dev/urandom (or Windows equivalent) to incorporate entropy gathered by the operating system. So the
 * key pairs are generated deterministically, but key agreement uses true random numbers.
 * <p>
 * At the time this class is first being written, neither TLS 1.3 nor Java 9 are available. As they become available, it
 * may become appropriate to switch from ECDSA/ECDHE to something based on Ed25519, for increased speed, decreased
 * bandwidth usage, and better safety (e.g., not needing strong random numbers for key agreement). But when (or whether)
 * that change happens will depend on whether standards such as the CNSA Suite are updated. In the longer term, this may
 * be upgraded to a post quantum algorithm (or a hybrid using both pre-quantum and post-quantum). But again, this will
 * depend on a number of factors. The plan is to continue to follow the national standard (currently CNSA Suit),
 * changing the algorithms as the standard changes.
 */
public class KeysAndCertsGenerator {
    // size of each symmetric key, in bytes
    public static final int SYM_KEY_SIZE_BYTES = 32; // 256 bits
    // number of bytes in a hash
    public static final int HASH_SIZE_BYTES = 48; // 384 bits (= 3*128)

    /**
     * Convert an int to a byte array, little endian.
     *
     * @param value the int to convert
     * @return the byte array
     */
    public static byte[] intToBytes(final int value) {
        final byte[] dst = new byte[Integer.BYTES];

        for (int i = 0; i < Integer.BYTES; i++) {
            final int shift = i * 8;
            dst[i] = (byte) (0xff & (value >> shift));
        }
        return dst;
    }

    private static final String PRNG_TYPE = "SHA1PRNG";
    private static final String PRNG_PROVIDER = "SUN";

    static SecureRandom getDetRandom() throws NoSuchProviderException, NoSuchAlgorithmException {
        return SecureRandom.getInstance(PRNG_TYPE, PRNG_PROVIDER);
    }

    private static final int MASTER_KEY_MULTIPLIER = 157;
    private static final int SWIRLD_ID_MULTIPLIER = 163;
    private static final int BITS_IN_BYTE = 8;

    private static final int SIG_SEED = 2;
    private static final int AGR_SEED = 0;

    private KeysAndCertsGenerator() {}

    /**
     * Creates an instance holding all the keys and certificates. This also generates the key pairs and certs and CSPRNG
     * state. The key pairs are generated as a function of the seed. The seed is the combination of the three
     * parameters. The signing key pair is used to sign all 3 certs.
     *
     * @param nodeId the node identifier
     */
    public static KeysAndCerts generate(final NodeId nodeId)
            throws NoSuchAlgorithmException, NoSuchProviderException, KeyStoreException, KeyGeneratingException {

        final byte[] masterKey = new byte[SYM_KEY_SIZE_BYTES];
        final byte[] swirldId = new byte[HASH_SIZE_BYTES];
        final int i = (int) nodeId.id();
        for (int j = 0; j < masterKey.length; j++) {
            masterKey[j] = (byte) (j * MASTER_KEY_MULTIPLIER);
        }
        for (int j = 0; j < swirldId.length; j++) {
            swirldId[j] = (byte) (j * SWIRLD_ID_MULTIPLIER);
        }
        masterKey[0] = (byte) i;
        masterKey[1] = (byte) (i >> BITS_IN_BYTE);
        final byte[] memberId = intToBytes(i);

        // deterministic CSPRNG, used briefly then discarded
        final SecureRandom sigDetRandom = getDetRandom();
        sigDetRandom.setSeed(masterKey);
        sigDetRandom.setSeed(swirldId);
        sigDetRandom.setSeed(memberId);
        sigDetRandom.setSeed(SIG_SEED);

        // deterministic CSPRNG, used briefly then discarded
        final SecureRandom agrDetRandom = getDetRandom();
        agrDetRandom.setSeed(masterKey);
        agrDetRandom.setSeed(swirldId);
        agrDetRandom.setSeed(memberId);
        agrDetRandom.setSeed(AGR_SEED);

        return generate(nodeId, SigningSchema.RSA, sigDetRandom, agrDetRandom);
    }

    /**
     * Generated keys using the supplied randomness and creates certificates with those keys. The signing key pair is
     * used to sign both certs.
     *
     * @param nodeId       the node ID used for the certificate distinguished names
     * @param schema       the signing schema to use for the signing key pair
     * @param sigDetRandom the source of randomness for generating the signing key pair
     * @param agrDetRandom the source of randomness for generating the agreement key pair
     * @return the generated keys and certs
     */
    public static KeysAndCerts generate(
            final NodeId nodeId,
            final SigningSchema schema,
            final SecureRandom sigDetRandom,
            final SecureRandom agrDetRandom)
            throws NoSuchAlgorithmException, NoSuchProviderException, KeyGeneratingException {
        final KeyPairGenerator agrKeyGen =
                KeyPairGenerator.getInstance(CryptoConstants.AGR_TYPE, CryptoConstants.AGR_PROVIDER);
        agrKeyGen.initialize(CryptoConstants.AGR_KEY_SIZE_BITS, agrDetRandom);

        final KeyPair sigKeyPair = generateKeyPair(schema, sigDetRandom);
        final KeyPair agrKeyPair = agrKeyGen.generateKeyPair();

        final String nodeName = nodeId.formatNodeName();
        final String dnS = CryptoStatic.distinguishedName("s-" + nodeName);
        final String dnA = CryptoStatic.distinguishedName("a-" + nodeName);

        // create the 2 certs (java.security.cert.Certificate)
        // both are signed by sigKeyPair, so sigCert is self-signed
        final X509Certificate sigCert = CryptoStatic.generateCertificate(
                dnS, sigKeyPair, dnS, sigKeyPair, sigDetRandom, schema.getSigningAlgorithm());
        final X509Certificate agrCert = CryptoStatic.generateCertificate(
                dnA, agrKeyPair, dnS, sigKeyPair, agrDetRandom, schema.getSigningAlgorithm());
        return new KeysAndCerts(sigKeyPair, agrKeyPair, sigCert, agrCert);
    }

    /**
     * Generates a new agreement key pair using {@link SecureRandom#getInstanceStrong()} as the CSPRNG.
     *
     * @return the generated agreement key pair
     */
    public static KeyPair generateAgreementKeyPair() throws NoSuchAlgorithmException, NoSuchProviderException {
        // getInstanceStrong() is no longer blocking - https://blogs.oracle.com/linux/post/rngd1
        final SecureRandom secureRandom = SecureRandom.getInstanceStrong();
        // generate the agreement key pair
        final KeyPairGenerator keyPairGenerator =
                KeyPairGenerator.getInstance(CryptoConstants.AGR_TYPE, CryptoConstants.AGR_PROVIDER);
        keyPairGenerator.initialize(CryptoConstants.AGR_KEY_SIZE_BITS, secureRandom);
        return keyPairGenerator.generateKeyPair();
    }
    /**
     * Generates a new key pair for the specified signing schema.
     *
     * @param signingSchema the signing schema
     * @param secureRandom  the source of randomness to use
     * @return the generated key pair
     */
    public static KeyPair generateKeyPair(final SigningSchema signingSchema, final SecureRandom secureRandom) {
        final KeyPairGenerator keyPairGen;
        try {
            keyPairGen = KeyPairGenerator.getInstance(signingSchema.getKeyType());
        } catch (final NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
        keyPairGen.initialize(signingSchema.getKeySizeBits(), secureRandom);
        return keyPairGen.generateKeyPair();
    }
}
