// SPDX-License-Identifier: Apache-2.0
package com.hedera.cryptography.ceremony;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/// TSS Ceremony Phase implementation.
class Phase {
    ///  The phase won't start until the initial file is present. Wait for 1 week because it's manual.
    private static final long WAIT_FOR_INITIAL_FILE_TIMEOUT_MILLIS = 7 * 24 * 60 * 60 * 1000;

    /// Regular processing on a node should be "fast", but we give it 12 hours of timeout before
    /// giving up and trying the previous node's file:
    private static final long WAIT_FOR_REGULAR_FILE_TIMEOUT_MILLIS = 12 * 60 * 60 * 1000;

    /// Phase number, e.g. "1", or "2"
    private final String phase;
    private final long thisNodeId;
    private final List<Long> allNodeIds;
    private final S3DirectoryAccessor s3DirectoryAccessor;
    private final DataCruncher dataCruncher;
    private final Crypto crypto;

    Phase(
            String phase,
            long thisNodeId,
            List<Long> allNodeIds,
            S3DirectoryAccessor s3DirectoryAccessor,
            DataCruncher dataCruncher,
            Crypto crypto) {
        this.phase = phase;
        this.thisNodeId = thisNodeId;
        this.allNodeIds = allNodeIds;
        this.s3DirectoryAccessor = s3DirectoryAccessor;
        this.dataCruncher = dataCruncher;
        this.crypto = crypto;
    }

    /// @return for -1 - "initial", otherwise the nodeId at the given index.
    private String nameAtIndex(int index) {
        if (index < 0) {
            return "initial";
        } else {
            return allNodeIds.get(index).toString();
        }
    }

    private String readyFileNameAtIndex(int index) {
        return nameAtIndex(index) + ".ready";
    }

    /// @return a previous index that is .ready, or MIN_VALUE if reached timeout
    private int waitForInputReady(int startExclusiveIndex) {
        // An index of a node that is supposed to process data generated by node at index `workingIndex-1`
        int workingIndex = startExclusiveIndex;

        do {
            String readyFileName = readyFileNameAtIndex(workingIndex - 1);
            System.err.println("Waiting for file: " + readyFileName);
            try {
                if (s3DirectoryAccessor.waitForFile(readyFileName, WAIT_FOR_REGULAR_FILE_TIMEOUT_MILLIS)) {
                    System.err.println("Found file: " + readyFileName);
                    return workingIndex - 1;
                }
            } catch (IOException e) {
                e.printStackTrace();
                // Don't give up just yet. Maybe you can pick up a previous file.
            }
        } while (--workingIndex >= 0);

        return Integer.MIN_VALUE;
    }

    /// Run the phase.
    /// If anything fails, simply return because it's okay to skip this phase and participate in the next phase if any.
    void run() {
        // Any IOException (from S3, file system, dataCruncher) simply returns from the method.
        // It's okay to skip one phase and process another.
        try {
            System.err.println("Starting phase " + phase + "...");

            // First, wait until the current phase actually starts - the initial file MUST be present.
            final String initialReadyFileName = readyFileNameAtIndex(-1);
            System.err.println("Waiting for the initial file: " + initialReadyFileName);
            if (!s3DirectoryAccessor.waitForFile(initialReadyFileName, WAIT_FOR_INITIAL_FILE_TIMEOUT_MILLIS)) {
                // 1 week has passed, the initial file never appeared.
                System.err.println("Timeout reached while waiting for the initial file. The phase cannot start.");
                return;
            }

            // Now wait for the actual input file for this node to process
            final int thisIndex = allNodeIds.indexOf(thisNodeId);
            final int inputIndex = waitForInputReady(thisIndex);
            if (inputIndex < -1) {
                System.err.println("Timeout reached while waiting for input data");
                return;
            }

            // We know the input file to process, let's claim it (we don't use the .claimed, it's for manual debugging.)
            final String inputFileName = nameAtIndex(inputIndex);
            final String thisFileName = nameAtIndex(thisIndex);
            s3DirectoryAccessor.writeText(thisFileName + ".claimed", inputFileName);
            System.err.println("Wrote: " + thisFileName + ".claimed" + " with inputFileName: " + inputFileName);

            System.err.println("Downloading input dir: " + inputFileName + ".bin");
            final Path inputDir;
            inputDir = s3DirectoryAccessor.downloadDir(inputFileName + ".bin");

            final String outputDirName = thisFileName + ".bin";
            System.err.println("Creating output dir: " + outputDirName);
            final Path outputDir;
            outputDir = Files.createTempDirectory(outputDirName);

            System.err.println("Processing input " + inputDir.toAbsolutePath().toString() + " and output result to "
                    + outputDir.toAbsolutePath().toString());
            final int exitCode = dataCruncher.execute(phase, inputDir, outputDir);
            if (exitCode != 0) {
                System.err.println("Error executing " + phase + ": " + exitCode);
                return;
            }

            System.err.println(
                    "Signing all the artifacts in " + outputDir.toAbsolutePath().toString());
            crypto.signDir(outputDir);

            // This will upload both the artifacts and their signatures and the signing cert generated just above:
            System.err.println(
                    "Uploading output from " + outputDir.toAbsolutePath().toString() + " to " + outputDirName);
            s3DirectoryAccessor.uploadDir(outputDir, outputDirName);

            System.err.println("Writing ready marker " + readyFileNameAtIndex(thisIndex));
            s3DirectoryAccessor.writeText(readyFileNameAtIndex(thisIndex), "");
            System.err.println("Wrote: " + readyFileNameAtIndex(thisIndex));

            System.err.println("Phase " + phase + " is complete.");
        } catch (IOException | RuntimeException e) {
            e.printStackTrace();
        }
    }
}
