/*
 * Copyright (C) 2024 Hedera Hashgraph, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hedera.cryptography.bls.test.fixtures;

import com.hedera.cryptography.bls.BlsKeyPair;
import com.hedera.cryptography.bls.BlsSignature;
import com.hedera.cryptography.bls.SignatureSchema;
import edu.umd.cs.findbugs.annotations.NonNull;
import java.util.List;
import java.util.Random;
import java.util.stream.Stream;

/**
 * Utility class used for testing purposes.
 */
public class BlsTestUtils {

    /**
     * Generates a list of key pairs.
     *
     * @param random        the random number generator
     * @param schema        the signature schema
     * @param numberOfPairs the number of key pairs to generate
     * @return the list of key pairs
     */
    public static @NonNull List<BlsKeyPair> generateKeyPairs(
            @NonNull final Random random, @NonNull final SignatureSchema schema, final int numberOfPairs) {
        return Stream.generate(() -> BlsKeyPair.generate(schema, random))
                .limit(numberOfPairs)
                .toList();
    }

    /**
     * Signs a message with a list of keys.
     *
     * @param pairs   the list of key pairs, the private keys of which will be used to sign the message
     * @param message the message to sign
     * @return the list of signatures
     */
    public static List<BlsSignature> bulkSign(@NonNull final List<BlsKeyPair> pairs, @NonNull final byte[] message) {
        return pairs.stream().map(p -> p.privateKey().sign(message)).toList();
    }

    /**
     * Generates random bytes.
     *
     * @param seed the seed to use for the random number generator
     * @param size the size of the byte array to generate
     * @return the generated byte array
     */
    public static @NonNull byte[] randomBytes(final long seed, final int size) {
        final byte[] bytes = new byte[size];
        new Random(seed).nextBytes(bytes);
        return bytes;
    }
}
