//
// Copyright (C) 2024 Hedera Hashgraph, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hedera_common_nativesupport_jni_Greeter */

#ifndef _Included_com_hedera_common_nativesupport_jni_Greeter
#define _Included_com_hedera_common_nativesupport_jni_Greeter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hedera_common_nativesupport_jni_Greeter
 * Method:    getGreeting
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hedera_common_nativesupport_jni_Greeter_getGreeting
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
