name: Build

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  packages: write
  contents: read
  issues: read
  checks: write
  pull-requests: write

env:
  LC_ALL: C.UTF-8
  GRADLE_CACHE_USERNAME: ${{ secrets.GRADLE_CACHE_USERNAME }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.GRADLE_CACHE_PASSWORD }}

jobs:
  build:
    name: Build TSS Crypto Library
    runs-on: network-node-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: temurin
          java-version: 21.0.4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          cache: false
          target: x86_64-pc-windows-msvc # additional target, Linux/Mac targets are configured as default

      - name: Setup Zig (Linux/Mac cross-compile)
        uses: mlugg/setup-zig@a67e68dc5c8281d9608136d3d7ca1b282213e4ac  # v1.2.1

      - name: Setup lld (Windows cross-compile)
        run: |
          sudo apt-get update
          sudo apt-get -y install lld libc6-dev

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-read-only: false

      - name: Build software
        run: ./gradlew assemble --scan

      - name: Spotless Check
        run: ./gradlew spotlessCheck --scan --continue

      - name: Dependency Scopes Check
        run: ./gradlew checkAllModuleInfo --scan --continue

      - name: Gradle Unit Test
        run: ./gradlew :reports:testCodeCoverageReport test --scan --continue

      - name: Publish Unit Test Results
        uses: step-security/publish-unit-test-result-action@4519d7c9f71dd765f8bbb98626268780f23bab28 # v2.17.0
        with:
          files: "**/build/test-results/test/TEST-*.xml"

  test-cross-platform:
    name: Test on ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [windows-2022, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Standardize Git Line Endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout Code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: temurin
          java-version: 21.0.4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-read-only: false

      - name: Gradle Unit Test
        run: ./gradlew test --scan --continue
