name: Build

on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

env:
  LC_ALL: C.UTF-8
  GRADLE_CACHE_USERNAME: ${{ secrets.GRADLE_CACHE_USERNAME }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.GRADLE_CACHE_PASSWORD }}