name: Publish Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  packages: write
  contents: read

env:
  LC_ALL: C.UTF-8
  GRADLE_CACHE_USERNAME: ${{ secrets.GRADLE_CACHE_USERNAME }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.GRADLE_CACHE_PASSWORD }}

jobs:
  build:
    name: Publish Release
    runs-on: network-node-auxiliary-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          java-version: 21.0.1

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
        with:
          cache-read-only: false

      - name: Publish Maven Central
        env:
          NEXUS_USERNAME: ${{ secrets.SVCS_OSSRH_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.SVCS_OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
        run: |
          ./gradlew releaseMavenCentralSnapshot -PpublishingPackageGroup=com.hedera.common --scan -PpublishSigningEnabled=true --no-configuration-cache
          ./gradlew releaseMavenCentralSnapshot -PpublishingPackageGroup=com.hedera.cryptography --scan -PpublishSigningEnabled=true --no-configuration-cache
