name: Publish Release

on:
  workflow_call:

defaults:
  run:
    shell: bash

permissions:
  packages: write
  contents: read

env:
  LC_ALL: C.UTF-8
  GRADLE_CACHE_USERNAME: ${{ secrets.GRADLE_CACHE_USERNAME }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.GRADLE_CACHE_PASSWORD }}

jobs:
  publish:
    name: Publish To Maven Central
    runs-on: [ self-hosted, Linux, medium, ephemeral ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Expand Shallow Clone for and Spotless
        if: ${{ (inputs.enable-unit-tests || inputs.enable-spotless-check) && !cancelled() }}
        run: git fetch --unshallow --no-recurse-submodules

      - name: Publish Maven Central
        env:
          NEXUS_USERNAME: ${{ secrets.SVCS_OSSRH_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.SVCS_OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
        run: |
          ./gradlew releaseMavenCentralSnapshot -PpublishingPackageGroup=com.hedera.cryptography --scan -PpublishSigningEnabled=true --no-configuration-cache
          ./gradlew releaseMavenCentralSnapshot -PpublishingPackageGroup=com.hedera.common --scan -PpublishSigningEnabled=true --no-configuration-cache
